{% set name = "owlrl" %}
{% set version = "5.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: efdebe76cf9ad148f316a9ae92e898e12b3b3690bd90218c898a2b676955b266
    patches:
      - 0001-remove-scripts.patch
  - folder: src
    url: https://github.com/RDFLib/OWL-RL/archive/v{{ version }}.tar.gz
    sha256: ec0a7c1496aba88fdad2b2709c7d0e75031fb18ac1d00ecdb861e687cad6949e

build:
  noarch: python
  number: 0
  entry_points:
    - owlrl = owlrl._cli:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - rdflib >=4.2.2
    - rdflib-jsonld >=0.4.0

test:
  source_files:
    - src/test
  requires:
    - pytest-cov
  imports:
    - owlrl
  commands:
    - owlrl --help
    - cd src && cd test && pytest --cov=owlrl -k "not dt_not_type and not maxqc1" -vv

about:
  home: https://github.com/RDFLib/OWL-RL
  license: W3C
  license_family: OTHER
  license_file: w3c.txt
  summary: 'OWL-RL and RDFS based RDF Closure inferencing for Python'
  description: |
    A simple implementation of the OWL2 RL Profile, as well as a basic RDFS
    inference, on top of RDFLib. Based mechanical forward chaining.
  doc_url: https://owl-rl.readthedocs.io
  doc_source_url: https://github.com/RDFLib/OWL-RL/blob/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
