{% set version = "7.1.1" %}
# the `if` avoids bot dupes
{% if 1 %}
  {% set pytest_skips = "not dt_not_type and not maxqc1" %}
  {% set cov_fail_under = 49 %}
{% endif %}

package:
  name: owlrl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/owlrl/owlrl-{{ version }}.tar.gz
  sha256: 0c3e18b7603907cf9e33367152a18d6366a8bb8ef083d1f1a166f71f0985cea7

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.10
  run:
    - python >=3.10
    - rdflib >=7.1.1

test:
  source_files:
    - test
  requires:
    - coverage
    - pytest
  imports:
    - owlrl
  commands:
    - cd test
    - coverage run --source=owlrl --branch -m pytest -vv --tb=long --color=yes -k "{{ pytest_skips }}"
    - coverage report --show-missing --skip-covered --fail-under={{ cov_fail_under }}

about:
  home: https://github.com/RDFLib/OWL-RL
  license: W3C
  license_family: OTHER
  license_file: LICENSE.txt
  summary: OWL-RL and RDFS based RDF Closure inferencing for Python
  description: |
    A simple implementation of the OWL2 RL Profile, as well as a basic RDFS
    inference, on top of RDFLib. Based mechanical forward chaining.
  doc_url: https://owl-rl.readthedocs.io
  doc_source_url: https://github.com/RDFLib/OWL-RL/blob/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
