{% set version = "7.1.4" %}
# the `if` avoids bot dupes
{% if 1 %}
  {% set pytest_skips = "not dt_not_type and not maxqc1" %}
  {% set cov_fail_under = 47 %}
{% endif %}

package:
  name: owlrl
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/o/owlrl/owlrl-{{ version }}.tar.gz
    sha256: 60bd4067e346b9111f0a2924565afe97ac6595b98b2bbe953928b5113971daf7
  - folder: src
    url: https://github.com/RDFLib/OWL-RL/archive/refs/tags/{{ version }}.tar.gz
    sha256: d93144039968f1ae39f3047bf5681f59616976cdd51f681a7c196afd82235506

build:
  noarch: python
  number: 0
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - rdflib >=7.1.3

test:
  source_files:
    - src/test
  requires:
    - coverage
    - pytest
    - python {{ python_min }}
  imports:
    - owlrl
  commands:
    - cd src/test
    - coverage run --source=owlrl --branch -m pytest -vv --tb=long --color=yes -k "{{ pytest_skips }}"
    - coverage report --show-missing --skip-covered --fail-under={{ cov_fail_under }}

about:
  home: https://github.com/RDFLib/OWL-RL
  license: W3C
  license_family: OTHER
  license_file: dist/LICENSE.txt
  summary: OWL-RL and RDFS based RDF Closure inferencing for Python
  description: |
    A simple implementation of the OWL2 RL Profile, as well as a basic RDFS
    inference, on top of RDFLib. Based mechanical forward chaining.
  doc_url: https://owl-rl.readthedocs.io
  doc_source_url: https://github.com/RDFLib/OWL-RL/blob/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
