{% set version = "7.1.1" %}

package:
  name: owlrl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/owlrl/owlrl-{{ version }}.tar.gz
  sha256: 0c3e18b7603907cf9e33367152a18d6366a8bb8ef083d1f1a166f71f0985cea7
  patches:
    - 0001-remove-scripts.patch

build:
  noarch: python
  number: 0
  entry_points:
    - owlrl = owlrl._cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - rdflib >=5.0.0

test:
  source_files:
    - test
  requires:
    - pytest-cov
  imports:
    - owlrl
  commands:
    - owlrl --help
    - cd test && pytest --cov=owlrl -k "not dt_not_type and not maxqc1" -vv --cov-report term-missing:skip-covered --cov-fail-under 49

about:
  home: https://github.com/RDFLib/OWL-RL
  license: W3C
  license_family: OTHER
  license_file: LICENSE.txt
  summary: OWL-RL and RDFS based RDF Closure inferencing for Python
  description: |
    A simple implementation of the OWL2 RL Profile, as well as a basic RDFS
    inference, on top of RDFLib. Based mechanical forward chaining.
  doc_url: https://owl-rl.readthedocs.io
  doc_source_url: https://github.com/RDFLib/OWL-RL/blob/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
