{% set name = "owlrl" %}
{% set version = "5.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: b1891d75b2c2fb0db9e1504a9b12dab738ed89236414c51393d1030597004342
    patches:
      - 0001-remove-scripts.patch
  - folder: src
    url: https://github.com/RDFLib/OWL-RL/archive/v{{ version }}.tar.gz
    sha256: f13cb3a7c30cbb6f9e4cf2eeddca2a526a3ccf26b13741e838ec6891656b9e0d

build:
  noarch: python
  number: 0
  entry_points:
    - owlrl = owlrl._cli:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - rdflib >=4.2.2
    - rdflib-jsonld >=0.4.0

test:
  source_files:
    - src/test
  requires:
    - pytest-cov
  imports:
    - owlrl
  commands:
    - owlrl --help
    - cd src && cd test && pytest --cov=owlrl -k "not dt_not_type and not maxqc1" -vv

about:
  home: https://github.com/RDFLib/OWL-RL
  license: W3C
  license_family: OTHER
  license_file: w3c.txt
  summary: OWL-RL and RDFS based RDF Closure inferencing for Python
  description: |
    A simple implementation of the OWL2 RL Profile, as well as a basic RDFS
    inference, on top of RDFLib. Based mechanical forward chaining.
  doc_url: https://owl-rl.readthedocs.io
  doc_source_url: https://github.com/RDFLib/OWL-RL/blob/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
