# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 7.1.4
  pytest_skips: not (dt_not_type or maxqc1)
  cov_fail_under: 47

package:
  name: owlrl
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/owlrl/owlrl-${{ version }}.tar.gz
    sha256: 60bd4067e346b9111f0a2924565afe97ac6595b98b2bbe953928b5113971daf7
    target_directory: dist
  - url: https://github.com/RDFLib/OWL-RL/archive/refs/tags/${{ version }}.tar.gz
    sha256: d93144039968f1ae39f3047bf5681f59616976cdd51f681a7c196afd82235506
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - rdflib >=7.1.4

tests:
  - python:
      imports: owlrl
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - src/test/
    requirements:
      run:
        - coverage
        - pytest
        - python ${{ python_min }}.*
    script:
      - cd src/test
      - python -c "from owlrl import __version__ as v; print(v); assert v == '${{ version }}'"
      - python -c "from importlib.metadata import version; v = version('owlrl'); print(v); assert v == '${{ version }}'"
      - coverage run --source=owlrl --branch -m pytest -vv --tb=long --color=yes -k "${{ pytest_skips }}"
      - coverage report --show-missing --skip-covered --fail-under=${{ cov_fail_under }}

about:
  license: W3C
  license_file: dist/LICENSE.txt
  summary: OWL-RL and RDFS based RDF Closure inferencing for Python
  description: |
    A simple implementation of the OWL2 RL Profile, as well as a basic RDFS
    inference, on top of RDFLib. Based mechanical forward chaining.
  homepage: https://github.com/RDFLib/OWL-RL
  documentation: https://owl-rl.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
