travis:
  secure:
    BINSTAR_TOKEN: Zm+wfl6PlYcY9zErMtf7MK5J3C8PET+swuZlhtcOk6E0Qzh6vkzVm73rQ3USN3L5+ph9z1WXSMGsrL+KN95jSFwcvJiLsoKozDmJL2GJWavym9QBI7XLxk2P8ukI+XRop/88uXOhwmC13wUGz0n7IheizaxfyZCpLBXNXC1wwzndm/aVK/aLaXE1OpmK2FtqAc6U//Jt7hRyOXaQEV9snrYCU68fkjezDTD/nMiNCWlqZ3t2OuqyC6/PJ64RC4rPs+d7leGTh7HDqskKPOcxXEBq026MX3H/k/ANE4DwWrYgzfqsF8nq7ufXnbzOfLfdSPhEeqfccG4iYdH9m3YwB8FpRoEaWxveA2FYJ+i3qkDnh4rnwPHa5LbExmwQVOySMalhPZsfHlugogI4ac3P+xwzGjepz94jKK2NbwOCt9BU/zx9+Fv5Jx4whsLfKifO73vneXtN4Ya0k5NGyLP0HmYov1L6lK1esG2ND2Kxr+6baRQApZ9J0GHwpYQP/JmVb+VIevdpNmwx1rWGZOJ4qA1BaJ3rwWBMghSVu8CuRTE4Lo/mj/zrJX3WHMmPQ4GE4ofe5EBxeFqWdJJijlfdV2eB45AR/aqU/EFQ1idF/TvlPAV+uc52IKTiysY3m9E4PiHW2/IlEGhuYB0w7elr/BTQOA+bpbUkKjmAx6XWrQc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
